# Generated by Django 5.0.2 on 2024-02-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.station'),
        ),
    ]
