# Generated by Django 5.0.2 on 2024-03-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_booking_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
